# Generated by Django 4.1.7 on 2023-03-10 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=20)),
                ('instructor', models.CharField(max_length=20)),
                ('rating', models.FloatField()),
                ('price', models.FloatField()),
            ],
        ),
    ]
